services:

  microfrontend-auth:
    build:
      context: auth
      dockerfile: ../Dockerfile.microfrontend
    ports:
      - 8081:8081

  microfrontend-profile:
    build:
      context: profile
      dockerfile: ../Dockerfile.microfrontend
    ports:
      - 8082:8082

  microfrontend-cards:
    build:
      context: cards
      dockerfile: ../Dockerfile.microfrontend
    ports:
      - 8083:8083

  microfrontend-host:
    build:
      context: host
      dockerfile: ../Dockerfile.microfrontend
    ports:
      - 8080:8080
    depends_on:
      microfrontend-auth:
        condition: service_started
      microfrontend-profile:
        condition: service_started
      microfrontend-cards:
        condition: service_started